name: textmining-labs
dependencies:
  - jupyter=1.0.0
  - matplotlib=2.2.2
  - scikit-learn=0.20.2
  - pandas=0.23.0
  - spacy=2.0.16
  - seaborn=0.9.0
  - gensim=3.4.0
  - pip:
    - wordcloud==1.5.0
