name: deeplearning-labs
channels:
  - defaults
  - pytorch
dependencies:
  - keras=2.3.1
  - jupyter=1.0.0
  - nb_conda=2.2.1
  - matplotlib=2.2.2
  - pandas=0.23.0
  - pip=19.3.1
  - pytorch=1.4.0
  - requests=2.22.0
  - scikit-image=0.14
  - scikit-learn=0.22.1
  - tensorflow=1.*
  - torchvision=0.5.0
  - pip:
    - eli5==0.10.1
    - scikit-optimize==0.5.2
    - transformers==2.5.1
