name: deeplearning-labs-gpu
channels:
  - conda-forge
dependencies:
  - cudatoolkit==9.0
  - cudnn==7.1.4
  - keras-gpu=2.2.2
  - jupyter=1.0.0
  - matplotlib=2.2.2
  - scikit-learn=0.19.1
  - pandas=0.23.0
  - scikit-image=0.14
  - scikit-optimize==0.5.2
