name: deeplearning-labs
channels:
  - conda-forge
dependencies:
  - keras=2.2.2
  - jupyter=1.0.0
  - matplotlib=2.2.2
  - scikit-learn=0.19.1
  - pandas=0.23.0
  - scikit-image=0.14
  - scikit-optimize==0.5.2
