name: deeplearning-labs-gpu
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - cudatoolkit>=8
  - cudnn>=7
  - keras-gpu=2.3.1
  - jupyter=1.0.0
  - matplotlib=2.2.2
  - scikit-learn=0.22.1
  - pandas=0.23.0
  - pip=19.3.1
  - pytorch=1.4.*
  - requests=2.22.0
  - scikit-image=0.14
  - tensorflow-gpu=1.*
  - torchvision=0.5.*
  - pip:
    - eli5==0.10.1
    - pillow==5.3
    - scikit-optimize==0.5.2
    - transformers==2.5.1
