name: deeplearning-labs
dependencies:
  - cudatoolkit==9.0
  - cudnn==7.1.2
  - keras-gpu=2.1.5
  - jupyter=1.0.0
  - nb_conda=2.2.1
  - matplotlib=2.2.2
  - scikit-learn=0.19.1
  - pandas=0.23.0
  - scikit-image=0.14
  - pip:
    - scikit-optimize==0.5.2
