name: ensembles-labs
channels:
  - defaults
  - conda-forge
dependencies:
  - ete3=3.1.1
  - jupyter=1.0.0
  - matplotlib=2.0.2
  - pandas=0.25.3
  - py-xgboost=0.80
  - scikit-learn=0.22
  - scikit-optimize=0.5.2
  - seaborn=0.9.0
